name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: version=$(jq -r .version package.json) && git tag -a "v$version" -m "Version $version"
