name: Test

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm install
      - run: git config --global user.email "i.ozguradem@gmail.com" && git config --global user.name "Özgür Adem Işıklı"
      - run: node src/test.js new axe-magic-api
